// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjWIbxsArUGylz1aLjWm5kM81UFNyP8Ro',
    appId: '1:291228293905:web:21af694573c3ff9aff4ab0',
    messagingSenderId: '291228293905',
    projectId: 'trombol-paradise-app',
    authDomain: 'trombol-paradise-app.firebaseapp.com',
    storageBucket: 'trombol-paradise-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFoknAonZiZJk6-f1Ef_CZN7COrFRiQc4',
    appId: '1:291228293905:android:944a3cd692ff48eaff4ab0',
    messagingSenderId: '291228293905',
    projectId: 'trombol-paradise-app',
    storageBucket: 'trombol-paradise-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg6r_2MBOdQV97hBJsELEap0723rDP9ew',
    appId: '1:291228293905:ios:82ae5d28838fdecfff4ab0',
    messagingSenderId: '291228293905',
    projectId: 'trombol-paradise-app',
    storageBucket: 'trombol-paradise-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterSkeleton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg6r_2MBOdQV97hBJsELEap0723rDP9ew',
    appId: '1:291228293905:ios:82ae5d28838fdecfff4ab0',
    messagingSenderId: '291228293905',
    projectId: 'trombol-paradise-app',
    storageBucket: 'trombol-paradise-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterSkeleton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjWIbxsArUGylz1aLjWm5kM81UFNyP8Ro',
    appId: '1:291228293905:web:a8d7037b2705d057ff4ab0',
    messagingSenderId: '291228293905',
    projectId: 'trombol-paradise-app',
    authDomain: 'trombol-paradise-app.firebaseapp.com',
    storageBucket: 'trombol-paradise-app.firebasestorage.app',
  );
}
